System.config({
  defaultJSExtensions: true,
  transpiler: "typescript",

  typescriptOptions: {
    "module": "commonjs",
    "emitDecoratorMetadata": true
  },

  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "app": "src"
  },
  bundles: {
    "lib/angular2-bundle.js": [
      "github:es-shims/es6-shim@0.33.0.js",
      "github:es-shims/es6-shim@0.33.0/es6-shim.js",
      "npm:reflect-metadata@0.1.0.js",
      "npm:reflect-metadata@0.1.0/Reflect.js",
      "npm:zone.js@0.5.2.js",
      "npm:zone.js@0.5.2/lib/zone.js",
      "npm:zone.js@0.5.2/lib/core.js",
      "npm:zone.js@0.5.2/lib/patch/browser.js",
      "npm:zone.js@0.5.2/lib/patch/promise.js",
      "npm:zone.js@0.5.2/lib/patch/event-target.js",
      "npm:zone.js@0.5.2/lib/patch/define-property.js",
      "npm:zone.js@0.5.2/lib/patch/websocket.js",
      "npm:zone.js@0.5.2/lib/patch/mutation-observer.js",
      "npm:zone.js@0.5.2/lib/patch/register-element.js",
      "npm:zone.js@0.5.2/lib/patch/property-descriptor.js",
      "npm:zone.js@0.5.2/lib/patch/functions.js",
      "npm:zone.js@0.5.2/lib/patch/geolocation.js",
      "npm:zone.js@0.5.2/lib/utils.js",
      "npm:angular2@2.0.0-alpha.34/src/facade/async.js",
      "npm:rx@2.5.1.js",
      "npm:angular2@2.0.0-alpha.34/src/facade/lang.js",
      "npm:rx@2.5.1/index.js",
      "npm:rx@2.5.1/dist/rx.js",
      "npm:rx@2.5.1/dist/rx.aggregates.js",
      "npm:rx@2.5.1/dist/rx.async.js",
      "npm:rx@2.5.1/dist/rx.backpressure.js",
      "npm:rx@2.5.1/dist/rx.binding.js",
      "npm:rx@2.5.1/dist/rx.coincidence.js",
      "npm:rx@2.5.1/dist/rx.experimental.js",
      "npm:rx@2.5.1/dist/rx.joinpatterns.js",
      "npm:rx@2.5.1/dist/rx.sorting.js",
      "npm:rx@2.5.1/dist/rx.virtualtime.js",
      "npm:rx@2.5.1/dist/rx.testing.js",
      "npm:rx@2.5.1/dist/rx.time.js",
      "github:jspm/nodelibs-process@0.1.1.js",
      "github:jspm/nodelibs-process@0.1.1/index.js",
      "npm:process@0.10.1.js",
      "npm:process@0.10.1/browser.js",
      "npm:angular2@2.0.0-alpha.34/di.js",
      "npm:angular2@2.0.0-alpha.34/src/di/metadata.js",
      "npm:angular2@2.0.0-alpha.34/src/di/decorators.js",
      "npm:angular2@2.0.0-alpha.34/src/di/forward_ref.js",
      "npm:angular2@2.0.0-alpha.34/src/di/injector.js",
      "npm:angular2@2.0.0-alpha.34/src/di/binding.js",
      "npm:angular2@2.0.0-alpha.34/src/di/key.js",
      "npm:angular2@2.0.0-alpha.34/src/di/exceptions.js",
      "npm:angular2@2.0.0-alpha.34/src/di/opaque_token.js",
      "npm:angular2@2.0.0-alpha.34/src/util/decorators.js",
      "npm:angular2@2.0.0-alpha.34/src/facade/collection.js",
      "npm:angular2@2.0.0-alpha.34/src/reflection/reflection.js",
      "npm:angular2@2.0.0-alpha.34/src/di/type_literal.js",
      "npm:angular2@2.0.0-alpha.34/src/reflection/reflector.js",
      "npm:angular2@2.0.0-alpha.34/src/reflection/reflection_capabilities.js",
      "npm:angular2@2.0.0-alpha.34/http.js",
      "npm:angular2@2.0.0-alpha.34/src/http/http.js",
      "npm:angular2@2.0.0-alpha.34/src/http/backends/xhr_backend.js",
      "npm:angular2@2.0.0-alpha.34/src/http/backends/jsonp_backend.js",
      "npm:angular2@2.0.0-alpha.34/src/http/backends/browser_xhr.js",
      "npm:angular2@2.0.0-alpha.34/src/http/backends/browser_jsonp.js",
      "npm:angular2@2.0.0-alpha.34/src/http/base_request_options.js",
      "npm:angular2@2.0.0-alpha.34/src/http/interfaces.js",
      "npm:angular2@2.0.0-alpha.34/src/http/base_response_options.js",
      "npm:angular2@2.0.0-alpha.34/src/http/backends/mock_backend.js",
      "npm:angular2@2.0.0-alpha.34/src/http/static_request.js",
      "npm:angular2@2.0.0-alpha.34/src/http/static_response.js",
      "npm:angular2@2.0.0-alpha.34/src/http/headers.js",
      "npm:angular2@2.0.0-alpha.34/src/http/enums.js",
      "npm:angular2@2.0.0-alpha.34/src/http/url_search_params.js",
      "npm:angular2@2.0.0-alpha.34/src/http/http_utils.js",
      "npm:angular2@2.0.0-alpha.34/router.js",
      "npm:angular2@2.0.0-alpha.34/src/core/application_tokens.js",
      "npm:angular2@2.0.0-alpha.34/src/router/router.js",
      "npm:angular2@2.0.0-alpha.34/src/router/instruction.js",
      "npm:angular2@2.0.0-alpha.34/src/router/router_link.js",
      "npm:angular2@2.0.0-alpha.34/src/core/annotations/decorators.js",
      "npm:angular2@2.0.0-alpha.34/src/core/annotations/annotations.js",
      "npm:angular2@2.0.0-alpha.34/src/core/annotations/view.js",
      "npm:angular2@2.0.0-alpha.34/src/core/annotations/di.js",
      "npm:angular2@2.0.0-alpha.34/src/core/annotations_impl/annotations.js",
      "npm:angular2@2.0.0-alpha.34/src/core/annotations_impl/view.js",
      "npm:angular2@2.0.0-alpha.34/src/core/annotations_impl/di.js",
      "npm:angular2@2.0.0-alpha.34/change_detection.js",
      "npm:angular2@2.0.0-alpha.34/src/render/api.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/change_detection.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/jit_proto_change_detector.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/pregen_proto_change_detector.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/proto_change_detector.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/pipes/pipes.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/differs/iterable_differs.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/differs/default_iterable_differ.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/differs/keyvalue_differs.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/differs/default_keyvalue_differ.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/pipes/observable_pipe.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/pipes/promise_pipe.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/pipes/uppercase_pipe.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/pipes/lowercase_pipe.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/pipes/json_pipe.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/pipes/limit_to_pipe.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/pipes/date_pipe.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/pipes/number_pipe.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/pipes/null_pipe.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/interfaces.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/parser/ast.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/parser/lexer.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/parser/parser.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/parser/locals.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/exceptions.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/constants.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/binding_record.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/directive_record.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/dynamic_change_detector.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/change_detector_ref.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/pipes/pipe.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/change_detection_jit_generator.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/coalesce.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/change_detection_util.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/proto_record.js",
      "npm:angular2@2.0.0-alpha.34/src/facade/math.js",
      "npm:angular2@2.0.0-alpha.34/src/facade/intl.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/abstract_change_detector.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/codegen_name_util.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/codegen_logic_util.js",
      "npm:angular2@2.0.0-alpha.34/src/profile/profile.js",
      "npm:angular2@2.0.0-alpha.34/src/change_detection/codegen_facade.js",
      "npm:angular2@2.0.0-alpha.34/src/profile/wtf_impl.js",
      "npm:angular2@2.0.0-alpha.34/src/router/route_registry.js",
      "npm:angular2@2.0.0-alpha.34/src/router/router_outlet.js",
      "npm:angular2@2.0.0-alpha.34/core.js",
      "npm:angular2@2.0.0-alpha.34/src/core/application_common.js",
      "npm:angular2@2.0.0-alpha.34/src/services/app_root_url.js",
      "npm:angular2@2.0.0-alpha.34/src/services/url_resolver.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/component_url_mapper.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/directive_resolver.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/compiler.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/view_manager.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/query_list.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/dynamic_component_loader.js",
      "npm:angular2@2.0.0-alpha.34/src/core/life_cycle/life_cycle.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/element_ref.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/template_ref.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/view_ref.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/view_container_ref.js",
      "npm:angular2@2.0.0-alpha.34/src/core/zone/ng_zone.js",
      "npm:angular2@2.0.0-alpha.34/src/dom/browser_adapter.js",
      "npm:angular2@2.0.0-alpha.34/src/dom/dom_adapter.js",
      "npm:angular2@2.0.0-alpha.34/src/core/exception_handler.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/view_loader.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/style_url_resolver.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/style_inliner.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/view_resolver.js",
      "npm:angular2@2.0.0-alpha.34/src/render/xhr.js",
      "npm:angular2@2.0.0-alpha.34/src/render/xhr_impl.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/events/event_manager.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/events/key_events.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/events/hammer_gestures.js",
      "npm:angular2@2.0.0-alpha.34/src/services/anchor_based_app_root_url.js",
      "npm:angular2@2.0.0-alpha.34/src/core/testability/testability.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/view_pool.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/view_manager_utils.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/view_listener.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/proto_view_factory.js",
      "npm:angular2@2.0.0-alpha.34/src/render/render.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/schema/element_schema_registry.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/schema/dom_element_schema_registry.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/view/shared_styles_host.js",
      "npm:angular2@2.0.0-alpha.34/src/profile/wtf_init.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/view.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/element_injector.js",
      "npm:angular2@2.0.0-alpha.34/src/dom/generic_browser_adapter.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/events/hammer_common.js",
      "npm:angular2@2.0.0-alpha.34/src/core/testability/get_testability.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/compiler.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/dom_renderer.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/dom_tokens.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/template_cloner.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/element_binder.js",
      "npm:angular2@2.0.0-alpha.34/src/core/compiler/directive_lifecycle_reflector.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/compile_pipeline.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/compile_step_factory.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/view/proto_view_merger.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/selector.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/util.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/view/proto_view.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/view/view.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/view/fragment.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/compile_element.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/compile_control.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/view/proto_view_builder.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/property_binding_parser.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/text_interpolation_parser.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/directive_parser.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/view_splitter.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/style_encapsulator.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/view/element_binder.js",
      "npm:angular2@2.0.0-alpha.34/src/render/dom/compiler/shadow_css.js",
      "npm:angular2@2.0.0-alpha.34/src/router/location_strategy.js",
      "npm:angular2@2.0.0-alpha.34/src/router/location.js",
      "npm:angular2@2.0.0-alpha.34/src/router/hash_location_strategy.js",
      "npm:angular2@2.0.0-alpha.34/src/router/pipeline.js",
      "npm:angular2@2.0.0-alpha.34/src/router/route_config_decorator.js",
      "npm:angular2@2.0.0-alpha.34/src/router/html5_location_strategy.js",
      "npm:angular2@2.0.0-alpha.34/src/router/route_definition.js",
      "npm:angular2@2.0.0-alpha.34/src/router/lifecycle_annotations.js",
      "npm:angular2@2.0.0-alpha.34/src/router/route_config_impl.js",
      "npm:angular2@2.0.0-alpha.34/src/router/route_lifecycle_reflector.js",
      "npm:angular2@2.0.0-alpha.34/src/router/route_config_nomalizer.js",
      "npm:angular2@2.0.0-alpha.34/src/router/route_recognizer.js",
      "npm:angular2@2.0.0-alpha.34/src/router/lifecycle_annotations_impl.js",
      "npm:angular2@2.0.0-alpha.34/src/router/path_recognizer.js",
      "npm:angular2@2.0.0-alpha.34/src/router/async_route_handler.js",
      "npm:angular2@2.0.0-alpha.34/src/router/sync_route_handler.js",
      "npm:angular2@2.0.0-alpha.34/src/router/helpers.js",
      "npm:angular2@2.0.0-alpha.34/src/router/url.js",
      "npm:angular2@2.0.0-alpha.34/angular2.js",
      "npm:angular2@2.0.0-alpha.34/annotations.js",
      "npm:angular2@2.0.0-alpha.34/forms.js",
      "npm:angular2@2.0.0-alpha.34/render.js",
      "npm:angular2@2.0.0-alpha.34/directives.js",
      "npm:angular2@2.0.0-alpha.34/profile.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/model.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/control_container.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/abstract_control_directive.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/ng_control_name.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/ng_form_control.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/ng_model.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/ng_control.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/ng_control_group.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/ng_form_model.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/ng_form.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/default_value_accessor.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/checkbox_value_accessor.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/select_control_value_accessor.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/validators.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/validators.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/form_builder.js",
      "npm:angular2@2.0.0-alpha.34/src/directives/ng_for.js",
      "npm:angular2@2.0.0-alpha.34/src/directives/ng_non_bindable.js",
      "npm:angular2@2.0.0-alpha.34/src/directives/ng_if.js",
      "npm:angular2@2.0.0-alpha.34/src/directives/ng_switch.js",
      "npm:angular2@2.0.0-alpha.34/src/directives/class.js",
      "npm:angular2@2.0.0-alpha.34/src/directives/ng_style.js",
      "npm:angular2@2.0.0-alpha.34/src/forms/directives/shared.js"
    ]
  },

  packages: {
    "app": {
      "defaultExtension": "ts",
      "main": "main.ts"
    }
  },

  map: {
    "angular2": "npm:angular2@2.0.0-alpha.34",
    "es6-shim": "github:es-shims/es6-shim@0.33.0",
    "reflect-metadata": "npm:reflect-metadata@0.1.0",
    "typescript": "lib/typescript.js",
    "zone.js": "npm:zone.js@0.5.2",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:angular2@2.0.0-alpha.34": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "reflect-metadata": "npm:reflect-metadata@0.1.0",
      "rx": "npm:rx@2.5.1",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "zone.js": "npm:zone.js@0.5.2"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:reflect-metadata@0.1.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:rx@2.5.1": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:zone.js@0.5.2": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    }
  }
});
